### PR TITLE
First reviewable.io pull request

### PR DESCRIPTION
**Pull request by benjaminsingleton**
Neha, please take a look!

---
This change is [Reviewable](https://reviewable.io/reviews/benjaminsingleton/crime-tips/3)

### CODE REVIEW

**Comment by benjaminsingleton** [comment]
Review status: 0 of 1 files reviewed at latest revision, 4 unresolved discussions.

---

*[src/views/UserSettings.js, line 29 at r1](https://reviewable.io:443/reviews/benjaminsingleton/crime-tips/3#-KkN1_O_qtKj1wGPs44w:-KkN1_O_qtKj1wGPs44x:b-ghn78e) ([raw file](https://github.com/benjaminsingleton/crime-tips/blob/dea89251f2440c29701ed5808bfd71f33d053180/src/views/UserSettings.js#L29)):*
> ```JavaScript
>     });
> 
>     firebaseApp.database().ref(`userActivity/${this.state.uid}`).limitToLast(5).on('value', (snapshot) => {
> ```

Here I query my logs (every time a user reads a tip, creates a new user, etc., etc.) and only display the 5 most recent actions.

---

*[src/views/UserSettings.js, line 126 at r1](https://reviewable.io:443/reviews/benjaminsingleton/crime-tips/3#-KkN2Op2gy_YpaBuE26q:-KkN2Op2gy_YpaBuE26r:b-6negg4) ([raw file](https://github.com/benjaminsingleton/crime-tips/blob/dea89251f2440c29701ed5808bfd71f33d053180/src/views/UserSettings.js#L126)):*
> ```JavaScript
>     const email = firebaseApp.auth().currentUser.email
> 
>     function activityText(key) {
> ```

Here I am generating part of the text of for user's activity feed depending on the type of activity. For example, if the activity has the value "important", the feed needs to display the text "User flagged the tip as important."

---

*[src/views/UserSettings.js, line 155 at r1](https://reviewable.io:443/reviews/benjaminsingleton/crime-tips/3#-KkN2sRQysR5c9kitY2u:-KkN2sRQysR5c9kitY2v:b-3uzldl) ([raw file](https://github.com/benjaminsingleton/crime-tips/blob/dea89251f2440c29701ed5808bfd71f33d053180/src/views/UserSettings.js#L155)):*
> ```JavaScript
>     let userActivityToDisplay = null
>     if (userActivity) {
>       const userActivityReversed = reverse(userActivity)
> ```

the reverse function reverses the order of items in an object. In this case, all the user activities need to be reversed so the most recent activity event appears first.

---

*[src/views/UserSettings.js, line 189 at r1](https://reviewable.io:443/reviews/benjaminsingleton/crime-tips/3#-KkN366RaQ1YJMMa9d1m:-KkN366RaQ1YJMMa9d1n:b4w4s89) ([raw file](https://github.com/benjaminsingleton/crime-tips/blob/dea89251f2440c29701ed5808bfd71f33d053180/src/views/UserSettings.js#L189)):*
> ```JavaScript
>                   <p>Current email: {email}</p>
>                   <p>Type in a new email (twice) to change it</p>
>                   <Message
> ```

this is semantic ui stuff

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/benjaminsingleton/crime-tips/3)*

**Comment by nrathi** [comment]
:lgtm:

---

Review status: 0 of 1 files reviewed at latest revision, 4 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/benjaminsingleton/crime-tips/3#-:-KkN4mjOxZq0eOn7kbzJ:bnfp4nl)*

**Comment by nrathi** [comment]
:lgtm_cancel: 

---

Review status: 0 of 1 files reviewed at latest revision, 4 unresolved discussions, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/benjaminsingleton/crime-tips/3#-:-KkN5RdozPc-P96UbcoU:b-qh6tsc)*

**Comment by nrathi** [comment]
Review status: 0 of 1 files reviewed at latest revision, 17 unresolved discussions, all commit checks successful.

---

*[src/views/UserSettings.js, line 20 at r1](https://reviewable.io:443/reviews/benjaminsingleton/crime-tips/3#-KkWch14-fhPHpCP1Bur:-KkWch19vU-tz7xGyDqQ:bofylyd) ([raw file](https://github.com/benjaminsingleton/crime-tips/blob/dea89251f2440c29701ed5808bfd71f33d053180/src/views/UserSettings.js#L20)):*
> ```JavaScript
>     newEmail: '',
>     newEmailRepeat: '',
>     emailMsg: ''
> ```

Why not null out these strings? 

---

*[src/views/UserSettings.js, line 24 at r1](https://reviewable.io:443/reviews/benjaminsingleton/crime-tips/3#-KkWcl2oHZlzg_TC-Ach:-KkWcl2pDNfJY3xOO6an:b-cyk4m5) ([raw file](https://github.com/benjaminsingleton/crime-tips/blob/dea89251f2440c29701ed5808bfd71f33d053180/src/views/UserSettings.js#L24)):*
> ```JavaScript
> 
>   componentWillMount = () => {
>     firebaseApp.database().ref(`users/${this.state.uid}`).on('value', (snapshot) => {
> ```

You don't need parenthesis around single params.

`snapshot => {`

---

*[src/views/UserSettings.js, line 26 at r1](https://reviewable.io:443/reviews/benjaminsingleton/crime-tips/3#-KkWcsnorReq8Ve8YkWu:-KkWcsnorReq8Ve8YkWv:b-t1by8t) ([raw file](https://github.com/benjaminsingleton/crime-tips/blob/dea89251f2440c29701ed5808bfd71f33d053180/src/views/UserSettings.js#L26)):*
> ```JavaScript
>     firebaseApp.database().ref(`users/${this.state.uid}`).on('value', (snapshot) => {
>       const userDetails = snapshot.val()
>       this.setState({ userDetails })
> ```

No point in separating out userDetails, here and below.

`snapshot => { this.setState({ userDetails: snapshot.val() }) };`

---

*[src/views/UserSettings.js, line 29 at r1](https://reviewable.io:443/reviews/benjaminsingleton/crime-tips/3#-KkN1_O_qtKj1wGPs44w:-KkWdCURzCCyWPJfhN3B:b-3f7tpy) ([raw file](https://github.com/benjaminsingleton/crime-tips/blob/dea89251f2440c29701ed5808bfd71f33d053180/src/views/UserSettings.js#L29)):*
<details><summary><i>Previously, benjaminsingleton (Benjamin Singleton) wrote…</i></summary><blockquote>

Here I query my logs (every time a user reads a tip, creates a new user, etc., etc.) and only display the 5 most recent actions.
</blockquote></details>

Max line length should be 100 chars. You can set this up in your editor, and a linter will catch it for you.

---

*[src/views/UserSettings.js, line 40 at r1](https://reviewable.io:443/reviews/benjaminsingleton/crime-tips/3#-KkWdQu9wClXmmYs2EmS:-KkWdQu9wClXmmYs2EmT:b-69tm2u) ([raw file](https://github.com/benjaminsingleton/crime-tips/blob/dea89251f2440c29701ed5808bfd71f33d053180/src/views/UserSettings.js#L40)):*
> ```JavaScript
>   }
> 
>   handleInputChange = (e, { name, value }) => this.setState({[name]: value})
> ```

I'm confused -- which aspect of state are you setting? 

---

*[src/views/UserSettings.js, line 43 at r1](https://reviewable.io:443/reviews/benjaminsingleton/crime-tips/3#-KkWdUbim0RtelSzPz8m:-KkWdUbim0RtelSzPz8n:b5hcqgc) ([raw file](https://github.com/benjaminsingleton/crime-tips/blob/dea89251f2440c29701ed5808bfd71f33d053180/src/views/UserSettings.js#L43)):*
> ```JavaScript
> 
>   onToggle = () => {
>     const notifications = !this.state.userDetails.notifications
> ```

Semicolons!!! At the end of all yo lines.

---

*[src/views/UserSettings.js, line 65 at r1](https://reviewable.io:443/reviews/benjaminsingleton/crime-tips/3#-KkWdb_kCNDGMWc8UIPb:-KkWdb_kCNDGMWc8UIPc:b-7ghawx) ([raw file](https://github.com/benjaminsingleton/crime-tips/blob/dea89251f2440c29701ed5808bfd71f33d053180/src/views/UserSettings.js#L65)):*
> ```JavaScript
>           passwordMsg: "Your password has been updated.",
>           newPassword: '',
>           newPasswordRepeat: ''
> ```

Change '' to null, errwhere. 

---

*[src/views/UserSettings.js, line 85 at r1](https://reviewable.io:443/reviews/benjaminsingleton/crime-tips/3#-KkWdi4Zlb1cKac2w7Rt:-KkWdi4Zlb1cKac2w7Ru:b74yhb3) ([raw file](https://github.com/benjaminsingleton/crime-tips/blob/dea89251f2440c29701ed5808bfd71f33d053180/src/views/UserSettings.js#L85)):*
> ```JavaScript
>   }
> 
>   changeEmail = (e) => {
> ```

No parens around e.

---

*[src/views/UserSettings.js, line 157 at r1](https://reviewable.io:443/reviews/benjaminsingleton/crime-tips/3#-KkWdtl7FLQvW3JExHdh:-KkWdtl7FLQvW3JExHdi:bz5bxrr) ([raw file](https://github.com/benjaminsingleton/crime-tips/blob/dea89251f2440c29701ed5808bfd71f33d053180/src/views/UserSettings.js#L157)):*
> ```JavaScript
>       const userActivityReversed = reverse(userActivity)
>       userActivityToDisplay = Object.keys(userActivityReversed).map(key =>  
>                                   <div key={key}>
> ```

Dafuq is this indentation.

Two spaces = one indent. Move this all over two spaces past "userActivityToDisplay".

---

*[src/views/UserSettings.js, line 163 at r1](https://reviewable.io:443/reviews/benjaminsingleton/crime-tips/3#-KkWe0T4LQcLJ1M6Ej5e:-KkWe0T4LQcLJ1M6Ej5f:b-i9bntm) ([raw file](https://github.com/benjaminsingleton/crime-tips/blob/dea89251f2440c29701ed5808bfd71f33d053180/src/views/UserSettings.js#L163)):*
> ```JavaScript
>                                   </div>)
>     }
>     
> ```

Trailing whitespace (bad).

---

*[src/views/UserSettings.js, line 175 at r1](https://reviewable.io:443/reviews/benjaminsingleton/crime-tips/3#-KkWe3OuXvz1nfbe2dEe:-KkWe3OuXvz1nfbe2dEf:bf59mse) ([raw file](https://github.com/benjaminsingleton/crime-tips/blob/dea89251f2440c29701ed5808bfd71f33d053180/src/views/UserSettings.js#L175)):*
> ```JavaScript
>                   <h3>Notifications</h3>
>                   <Radio 
>                     toggle
> ```

What is this? 

---

*[src/views/UserSettings.js, line 186 at r1](https://reviewable.io:443/reviews/benjaminsingleton/crime-tips/3#-KkWe6i6AlONxo2jCuXb:-KkWe6i6AlONxo2jCuXc:b74yhb3) ([raw file](https://github.com/benjaminsingleton/crime-tips/blob/dea89251f2440c29701ed5808bfd71f33d053180/src/views/UserSettings.js#L186)):*
> ```JavaScript
>                     error={this.state.emailMsgStatus === 'error'}
>                     success={this.state.emailMsgStatus === 'success'}
>                     onSubmit={(e) => this.changeEmail(e)}>
> ```

No parens around e.

---

*[src/views/UserSettings.js, line 255 at r1](https://reviewable.io:443/reviews/benjaminsingleton/crime-tips/3#-KkWeFVlzXfQw4xcX_o3:-KkWeFVlzXfQw4xcX_o4:blz54dw) ([raw file](https://github.com/benjaminsingleton/crime-tips/blob/dea89251f2440c29701ed5808bfd71f33d053180/src/views/UserSettings.js#L255)):*
> ```JavaScript
>                     color='violet' 
>                   />
>                   </Form>
> ```

These components are so similar to the ones above -- you should make a function that takes a parameter or two and spits out the right component. 

---

*[src/views/UserSettings.js, line 272 at r1](https://reviewable.io:443/reviews/benjaminsingleton/crime-tips/3#-KkWeRMYC40acc7dzkVD:-KkWeRMYC40acc7dzkVE:b-a1e281) ([raw file](https://github.com/benjaminsingleton/crime-tips/blob/dea89251f2440c29701ed5808bfd71f33d053180/src/views/UserSettings.js#L272)):*
> ```JavaScript
>     );
>   }
> }
> ```

You should have a trailing newline at the end of files.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/benjaminsingleton/crime-tips/3)*

**Comment by benjaminsingleton** [comment]
Review status: 0 of 1 files reviewed at latest revision, 17 unresolved discussions, all commit checks successful.

---

*[src/views/UserSettings.js, line 20 at r1](https://reviewable.io:443/reviews/benjaminsingleton/crime-tips/3#-KkWch14-fhPHpCP1Bur:-KkXl7LndpY6jz0idfnL:b-27jub2) ([raw file](https://github.com/benjaminsingleton/crime-tips/blob/dea89251f2440c29701ed5808bfd71f33d053180/src/views/UserSettings.js#L20)):*
<details><summary><i>Previously, nrathi (Neha Rathi) wrote…</i></summary><blockquote>

Why not null out these strings? 
</blockquote></details>

If you null out a string on a controlled component, it triggers the following warning: 
`Warning: 'value' prop on 'input' should not be null. Consider using the empty string to clear the component or 'undefined' for uncontrolled components.`

See how `this.state = {value: ''};` in https://facebook.github.io/react/docs/forms.html#controlled-components

---

*[src/views/UserSettings.js, line 40 at r1](https://reviewable.io:443/reviews/benjaminsingleton/crime-tips/3#-KkWdQu9wClXmmYs2EmS:-KkXornZRMFmngMVPNQS:b-7y6ry3) ([raw file](https://github.com/benjaminsingleton/crime-tips/blob/dea89251f2440c29701ed5808bfd71f33d053180/src/views/UserSettings.js#L40)):*
<details><summary><i>Previously, nrathi (Neha Rathi) wrote…</i></summary><blockquote>

I'm confused -- which aspect of state are you setting? 
</blockquote></details>

This function takes whatever is the HTML `name` of the input field and sets the value as the key in state. The state value is whatever is typed into the input field. For example, see line 240. The `name` is `newPassword` and the value is `123`. So this `this.setState({[name]: value})` becomes `this.setState({'newPassword': '123'})`

---

*[src/views/UserSettings.js, line 43 at r1](https://reviewable.io:443/reviews/benjaminsingleton/crime-tips/3#-KkWdUbim0RtelSzPz8m:-KkXofHYDsTkuIvE2PYV:b-c0gce7) ([raw file](https://github.com/benjaminsingleton/crime-tips/blob/dea89251f2440c29701ed5808bfd71f33d053180/src/views/UserSettings.js#L43)):*
<details><summary><i>Previously, nrathi (Neha Rathi) wrote…</i></summary><blockquote>

Semicolons!!! At the end of all yo lines.
</blockquote></details>

Lol. I really don't understand why javascript code runs without semicolons if they are so important. 

---

*[src/views/UserSettings.js, line 65 at r1](https://reviewable.io:443/reviews/benjaminsingleton/crime-tips/3#-KkWdb_kCNDGMWc8UIPb:-KkXqoqgzNv81m9K4XO3:bl3hlz9) ([raw file](https://github.com/benjaminsingleton/crime-tips/blob/dea89251f2440c29701ed5808bfd71f33d053180/src/views/UserSettings.js#L65)):*
<details><summary><i>Previously, nrathi (Neha Rathi) wrote…</i></summary><blockquote>

Change '' to null, errwhere. 
</blockquote></details>

See above. Needs to be empty string since it's a controlled component.

---

*[src/views/UserSettings.js, line 157 at r1](https://reviewable.io:443/reviews/benjaminsingleton/crime-tips/3#-KkWdtl7FLQvW3JExHdh:-KkXnS_LO0_KZS4ZsIcx:b-3hr2h0) ([raw file](https://github.com/benjaminsingleton/crime-tips/blob/dea89251f2440c29701ed5808bfd71f33d053180/src/views/UserSettings.js#L157)):*
> one indent. Move this all over two spaces past "user
Lol. It looked nice in my code editor!

---

*[src/views/UserSettings.js, line 175 at r1](https://reviewable.io:443/reviews/benjaminsingleton/crime-tips/3#-KkWe3OuXvz1nfbe2dEe:-KkXoHZ202l1DRi0TvLg:b-ze14bo) ([raw file](https://github.com/benjaminsingleton/crime-tips/blob/dea89251f2440c29701ed5808bfd71f33d053180/src/views/UserSettings.js#L175)):*
<details><summary><i>Previously, nrathi (Neha Rathi) wrote…</i></summary><blockquote>

What is this? 
</blockquote></details>

It's a toggle that makes it easy for the user to turn their email notifications when a new crime tip is submitted on or off. Added a screenshot to provide more context.


---


*Comments from [Reviewable](https://reviewable.io:443/reviews/benjaminsingleton/crime-tips/3)*

**Comment by benjaminsingleton** [comment]
Review status: 0 of 1 files reviewed at latest revision, 17 unresolved discussions, all commit checks successful.

---

*[src/views/UserSettings.js, line 24 at r1](https://reviewable.io:443/reviews/benjaminsingleton/crime-tips/3#-KkWcl2oHZlzg_TC-Ach:-KkXx-q2TAaVxf1mT0AB:bgy1qir) ([raw file](https://github.com/benjaminsingleton/crime-tips/blob/dea89251f2440c29701ed5808bfd71f33d053180/src/views/UserSettings.js#L24)):*
<details><summary><i>Previously, nrathi (Neha Rathi) wrote…</i></summary><blockquote>

You don't need parenthesis around single params.

`snapshot => {`
</blockquote></details>

According to ESlint, `[eslint] Expected parentheses around arrow function argument having a body with curly braces. (arrow-parens)`. So only if snapshot is on the same line should you not use parentheses.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/benjaminsingleton/crime-tips/3)*

**Pull request merged**
